#!/bin/bash

cd ..
source venv/bin/activate
TMPDIR=$(mktemp -d)
test -e results && mv results "$TMPDIR"
python orthrus.py -t all -f "tests/$1" --processes 20
test -e results && mv results tests
test -e "$TMPDIR" && mv "$TMPDIR" results
